# configuration of display in snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog

usage:
  mandatory-flags:
    desc: Call peaks with Macs2 and annotate them with Homer
    flags: FAIR Macs2 Snakemake Homer Deeptools
  software-stack-deployment:
    conda: true
    singularity: true
    singularity+conda: true
  report: true