# configuration of display in snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog

usage:
  mandatory-flags:
    desc: Call peaks with Macs2 and annotate them with Homer
    flags: --profile ./profiles/
  software-stack-deployment:
    conda: true
    singularity: false
    singularity+conda: false
  report: true