default-resources:
  runtime: 90
  mem_mb: 512
  tmpdir: "tmp"

set-threads:
  bowtie2_build: 20
  bowtie2_alignment: 20
  sambamba_sort: 6
  sambamba_view: 6
  sambamba_markdup: 6
  deeptools_fingerprint: 6
  deeptools_plotcoverage: 6
  deeptools_bamcoverage: 6


set-resources:
  bedtools_merge_blacklist:
    mem_mb: 3072
    runtime: 10
  samtools_index:
    mem_mb: 1024
    runtime: 10
  picard_create_dict:
    mem_mb: 4096
    runtime: 10
  bowtie2_build:
    mem_mb: 49152
    runtime: 105
  bowtie2_alignment:
    mem_mb: 49152
    runtime: 150
  sambamba_sort:
    mem_mb: 20480
  sambamba_view:
    mem_mb: 4096
  sambamba_markdup:
    mem_mb: 4096
  sambamba_index:
    mem_mb: 2048
  multiqc_report:
    mem_mb: 5120
    runtime: 30
  picard_create_multiple_metrics_raw:
    mem_mb: 6144
    runtime: 45
  picard_create_multiple_metrics:
    mem_mb: 6144
    runtime: 45
  deeptools_bamcoverage:
    mem_mb: 10240
    runtime: 60
  deeptools_plotcoverage:
    mem_mb: 10240
    runtime: 60
  deeptools_fingerprint:
    mem_mb: 10240
    runtime: 60