genomes: ./config/genomes.csv
params:
  fair_bowtie2_mapping_sambamba_view: "--format 'bam'"
  fair_macs2_calling_deeptools_plot_coverage: "--coverageThresholds 1"
  fair_macs2_calling_homer_annotate_peaks: "-homer2"
  fair_macs2_calling_macs2_callpeak: "--keep-dup all --pvalue 1"
  use_sieve: true
pipeline:
  name: fair_macs2_calling
  tag: 1.0.1
samples: .test/config/samples.csv
