samples: config/samples.csv

params:
  fair_bowtie2_mapping:
    sambamba:
      view: "--format 'bam'"
      markdup: ""
  fair_macs2_calling:
    macs2:
      callpeak: "--keep-dup all --pvalue 1"
    deeptools:
      plot_coverage: "--coverageThresholds 1"
    homer:
      annotatepeaks: "-homer2 "

# Optional path to a `genome.csv` file
genomes: config/genomes.csv

# Internal use only, not described in documentation.
# `false` deactivate import of fair_genome_indexer pipeline.
# Requires the file `genome.csv` to be filled.
# load_fair_genome_indexer: true
# `false` deactivate import of fair_bowtie2_mapping pipeline.
# Requires the file `samples.csv` to be filled with bam.
# load_fair_bowtie2_mapping: true
